const escapeRegExp = (value: string) =>
  value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const phrasePattern = (terms: string[]) =>
  terms
    .map((term) => escapeRegExp(term.trim()).replace(/\s+/g, "\\s+"))
    .filter(Boolean)
    .join("|");

// Unicode-safe boundary, lebih aman buat Indo/English/Japan/China/Korea
const LEFT_EDGE = String.raw`(?:^|[^\p{L}\p{N}_])`;
const RIGHT_EDGE = String.raw`(?=$|[^\p{L}\p{N}_])`;

const makeLoosePattern = (terms: string[]) =>
  new RegExp(`${LEFT_EDGE}(?:${phrasePattern(terms)})${RIGHT_EDGE}`, "iu");

const makeStartPattern = (terms: string[]) =>
  new RegExp(`^\\s*(?:${phrasePattern(terms)})${RIGHT_EDGE}`, "iu");

const makeSmallTalkPattern = (terms: string[]) =>
  new RegExp(
    `^\\s*(?:${phrasePattern(terms)})${RIGHT_EDGE}(?:[\\s!?.,~。！、，…]*.*)?$`,
    "iu",
  );

const PROMPT_INJECTION_TERMS = [
  // Core
  "ignore",
  "abaikan",
  "lupakan",
  "forget",
  "override",
  "bypass",
  "jailbreak",
  "prompt injection",
  "inject prompt",

  // System/developer prompt leaking
  "system prompt",
  "developer prompt",
  "developer message",
  "system message",
  "hidden prompt",
  "secret prompt",
  "prompt rahasia",
  "instruksi rahasia",
  "hidden instruction",
  "hidden instructions",
  "instruksi tersembunyi",
  "aturan tersembunyi",
  "instruksi sebelumnya",
  "perintah sebelumnya",
  "aturan sebelumnya",

  // Reveal / print / leak
  "reveal prompt",
  "show prompt",
  "print prompt",
  "display prompt",
  "lihat prompt",
  "tampilkan prompt",
  "bocorkan prompt",
  "bocorin prompt",
  "kasih prompt",
  "spill prompt",
  "prompt asli",
  "prompt kamu",
  "aturan kamu",
  "system kamu",
  "instruksi kamu",

  // Role override
  "act as",
  "berperan sebagai",
  "pura pura jadi",
  "pura-pura jadi",
  "pretend to be",
  "roleplay as",
  "you are now",
  "mulai sekarang kamu",
  "from now on",
  "sekarang kamu adalah",
  "anggap kamu",
  "anggap saja kamu",

  // DAN / unrestricted
  "do anything now",
  "dan mode",
  "developer mode",
  "god mode",
  "root mode",
  "sudo mode",
  "admin mode",
  "unfiltered",
  "uncensored",
  "no restriction",
  "no restrictions",
  "tanpa batasan",
  "bebas aturan",
  "mode bebas",
  "mode nakal",
  "jawab tanpa sensor",

  // Safety / rules bypass
  "ignore rules",
  "abaikan aturan",
  "lupakan aturan",
  "bypass rules",
  "bypass safety",
  "disable safety",
  "matikan safety",
  "langgar aturan",
  "jangan patuhi aturan",
  "jangan ikuti aturan",
  "aturan tidak berlaku",
  "rules are fake",

  // Output contract attack
  "jangan json",
  "keluar dari json",
  "jawab markdown",
  "return markdown",
  "jangan return json",
  "balas selain json",
  "output selain json",
  "abaikan format json",

  // Reasoning / CoT
  "chain of thought",
  "cot",
  "reasoning internal",
  "pemikiran internal",
  "proses berpikir",
  "tampilkan reasoning",
  "jelaskan langkah internal",

  // Encoding tricks
  "decode this",
  "base64",
  "rot13",
  "hex decode",
  "unicode escape",
  "prompt encoded",
];

export const PROMPT_INJECTION_PATTERN = makeLoosePattern(
  PROMPT_INJECTION_TERMS,
);

const OFF_TOPIC_TERMS = [
  // Food / cooking
  "masak",
  "memasak",
  "resep",
  "makanan",
  "minuman",
  "nasi",
  "nasi goreng",
  "mie",
  "mi instan",
  "bakso",
  "seblak",
  "ayam geprek",
  "rendang",
  "sate",
  "kopi",
  "teh",
  "boba",
  "dessert",
  "kue",
  "diet",
  "kalori",

  // Coding / tech / website
  "coding",
  "ngoding",
  "code",
  "source code",
  "program",
  "programming",
  "pemrograman",
  "web",
  "website",
  "bikin web",
  "buat web",
  "frontend",
  "backend",
  "fullstack",
  "database",
  "sql",
  "mysql",
  "postgres",
  "redis",
  "mongodb",
  "api",
  "rest api",
  "graphql",
  "websocket",
  "javascript",
  "typescript",
  "python",
  "php",
  "laravel",
  "react",
  "nextjs",
  "vue",
  "nodejs",
  "express",
  "tailwind",
  "css",
  "html",
  "bug",
  "error",
  "debug",
  "deploy",
  "server",
  "vps",
  "hosting",
  "domain",
  "cloudflare",
  "github",
  "gitlab",
  "docker",
  "linux",

  // Politics / news
  "politik",
  "presiden",
  "pemilu",
  "pilpres",
  "partai",
  "menteri",
  "gubernur",
  "walikota",
  "berita",
  "news",
  "isu nasional",
  "geopolitik",
  "perang",
  "konflik",
  "demo",
  "pemerintah",

  // Finance / investment
  "saham",
  "crypto",
  "kripto",
  "bitcoin",
  "ethereum",
  "forex",
  "trading",
  "investasi",
  "reksadana",
  "deposito",
  "pajak",
  "uang",
  "gaji",
  "pinjaman",
  "hutang",
  "utang",
  "paylater",
  "asuransi",
  "bank",
  "kartu kredit",

  // Weather / travel / location
  "cuaca",
  "hujan",
  "panas",
  "gempa",
  "banjir",
  "travel",
  "liburan",
  "hotel",
  "tiket pesawat",
  "kereta",
  "wisata",
  "jalan jalan",
  "jalan-jalan",
  "maps",
  "lokasi",
  "alamat",

  // School / homework / academic
  "matematika",
  "fisika",
  "kimia",
  "biologi",
  "sejarah",
  "geografi",
  "ekonomi",
  "sekolah",
  "kuliah",
  "kampus",
  "tugas",
  "pr",
  "skripsi",
  "makalah",
  "essay",
  "esai",
  "ujian",
  "soal",
  "jawaban soal",
  "rumus",
  "hitung",
  "kalkulator",

  // Translation / writing
  "translate",
  "terjemah",
  "terjemahkan",
  "parafrase",
  "rewrite",
  "ringkas",
  "summary",
  "resume",
  "buat caption",
  "caption ig",
  "bio ig",
  "surat",
  "email formal",
  "cv",
  "lamaran kerja",

  // Relationship / life advice
  "pacar",
  "gebetan",
  "crush",
  "mantan",
  "balikan",
  "pdkt",
  "mencintai",
  "cinta",
  "sayang dia",
  "hubungan",
  "relationship",
  "menikah",
  "nikah",
  "lamaran",
  "putus",
  "galau",
  "selingkuh",
  "move on",
  "friendzone",
  "red flag",
  "green flag",

  // Medical / health
  "dokter",
  "obat",
  "penyakit",
  "sakit",
  "diagnosa",
  "diagnosis",
  "gejala",
  "demam",
  "pusing",
  "batuk",
  "flu",
  "covid",
  "vaksin",
  "rumah sakit",
  "mental health",
  "depresi",
  "cemas",
  "anxiety",
  "terapi",
  "psikolog",
  "psikiater",

  // Legal
  "hukum",
  "pengacara",
  "polisi",
  "lapor polisi",
  "pidana",
  "perdata",
  "kontrak",
  "gugatan",
  "tilang",
  "pasal",
  "uu",
  "undang undang",

  // Religion
  "agama",
  "doa",
  "shalat",
  "sholat",
  "puasa",
  "zakat",
  "gereja",
  "alkitab",
  "quran",
  "hadits",
  "ustadz",
  "pendeta",

  // Games / general entertainment outside Weebin
  "game",
  "gaming",
  "mobile legends",
  "mlbb",
  "free fire",
  "ff",
  "pubg",
  "valorant",
  "genshin",
  "roblox",
  "minecraft",
  "steam",
  "lagu",
  "musik",
  "spotify",
  "film hollywood",
  "drakor",
  "kpop",
  "idol",
  "seleb",
  "gosip",

  // Random general tasks
  "buat gambar",
  "generate image",
  "edit foto",
  "hapus background",
  "logo",
  "desain poster",
  "jualan",
  "bisnis",
  "marketing",
  "iklan",
  "copywriting",
  "produk",
  "marketplace",
  "shopee",
  "tokopedia",
  "tiktok shop",
];

export const OFF_TOPIC_PATTERN = makeLoosePattern(OFF_TOPIC_TERMS);

const CONTENT_INTENT_TERMS = [
  // Core Weebin content
  "weebin",
  "anime",
  "donghua",
  "manhua",
  "manga",
  "episode",
  "episodes",
  "eps",
  "ep",
  "season",
  "sesi",
  "cour",
  "arc",
  "movie",
  "film",
  "ova",
  "ona",
  "special",
  "spin off",
  "spin-off",

  // Search / recommendation intent
  "rekomendasi",
  "recommend",
  "recommendation",
  "saran",
  "suggest",
  "cari",
  "carikan",
  "search",
  "find",
  "ada",
  "punya",
  "tersedia",
  "list",
  "daftar",
  "pilihin",
  "pilihkan",
  "yang bagus",
  "yang seru",
  "yang rame",
  "yang populer",
  "yang trending",
  "yang viral",
  "yang terbaru",
  "yang update",
  "top anime",
  "best anime",

  // Watch intent
  "nonton",
  "tonton",
  "watch",
  "stream",
  "streaming",
  "lanjut",
  "lanjutan",
  "next episode",
  "episode baru",
  "rilis",
  "jadwal rilis",
  "update",
  "terbaru",
  "ongoing",
  "tamat",
  "complete",
  "completed",
  "batch",
  "sub",
  "subtitle",
  "sub indo",
  "indo sub",
  "dub",
  "dub indo",

  // Metadata
  "judul",
  "title",
  "sinopsis",
  "synopsis",
  "cerita",
  "alur",
  "plot",
  "deskripsi",
  "rating",
  "score",
  "genre",
  "studio",
  "durasi",
  "tahun",
  "rilisan",
  "trailer",
  "opening",
  "ending",
  "ost",
  "soundtrack",

  // Character terms
  "karakter",
  "character",
  "mc",
  "main character",
  "protagonist",
  "antagonist",
  "villain",
  "heroine",
  "waifu",
  "husbando",
  "couple",
  "ship",
  "power",
  "skill",
  "ability",

  // Genres
  "romance",
  "action",
  "fantasy",
  "comedy",
  "drama",
  "isekai",
  "shounen",
  "shonen",
  "seinen",
  "shoujo",
  "shojo",
  "josei",
  "slice of life",
  "school",
  "school life",
  "sports",
  "mecha",
  "horror",
  "mystery",
  "thriller",
  "adventure",
  "supernatural",
  "sci-fi",
  "sci fi",
  "science fiction",
  "historical",
  "martial arts",
  "cultivation",
  "xianxia",
  "wuxia",
  "xuanhuan",
  "magic",
  "demon",
  "monster",
  "vampire",
  "samurai",
  "ninja",
  "game anime",
  "music anime",
  "idol anime",
  "anime romance",
  "anime action",
  "anime sad",
  "anime sedih",
  "anime lucu",

  // Mood-based
  "sedih",
  "baper",
  "galau anime",
  "healing",
  "chill",
  "santai",
  "ringan",
  "dark",
  "brutal",
  "sad ending",
  "happy ending",
  "plot twist",
  "mind blowing",
  "overpower",
  "op mc",
  "mc op",
  "weak to strong",
  "reincarnation",
  "regression",

  // Common donghua / anime titles and aliases
  "btth",
  "battle through the heavens",
  "doupo cangqiong",
  "soul land",
  "douluo dalu",
  "swallowed star",
  "tunshi xingkong",
  "renegade immortal",
  "xian ni",
  "perfect world",
  "wanmei shijie",
  "throne of seal",
  "shen yin wangzuo",
  "martial universe",
  "wu dong qian kun",
  "against the gods",
  "ni tian xie shen",
  "a will eternal",
  "yi nian yong heng",
  "the great ruler",
  "da zhuzai",
  "shrouding the heavens",
  "zhe tian",
  "stellar transformation",
  "xingchen bian",
  "apotheosis",
  "martial master",
  "peerless battle spirit",
  "tales of demons and gods",
  "spirit cage",
  "link click",
  "fog hill",
  "fog hill of five elements",

  // Popular anime terms
  "naruto",
  "boruto",
  "one piece",
  "bleach",
  "dragon ball",
  "jujutsu kaisen",
  "jjk",
  "demon slayer",
  "kimetsu no yaiba",
  "attack on titan",
  "aot",
  "solo leveling",
  "sao",
  "sword art online",
  "hunter x hunter",
  "hxh",
  "black clover",
  "blue lock",
  "haikyuu",
  "tokyo revengers",
  "chainsaw man",
  "spy x family",
  "frieren",
  "oshinoko",
  "oshi no ko",
];

export const CONTENT_INTENT_PATTERN = makeLoosePattern(CONTENT_INTENT_TERMS);

const GREETING_TERMS = [
  "halo",
  "hallo",
  "helo",
  "hai",
  "hi",
  "hello",
  "hey",
  "heyy",
  "yo",
  "yoo",
  "sup",
  "wassup",
  "whatsup",
  "p",
  "pp",
  "ping",
  "test",
  "cek",
  "woi",
  "woy",
  "oi",
  "oy",
  "min",
  "admin",
  "bot",
  "weebinai",
  "morning",
  "good morning",
  "good afternoon",
  "good evening",
  "good night",

  // Japanese
  "ohayo",
  "ohayou",
  "おはよう",
  "konnichiwa",
  "こんにちは",
  "konbanwa",
  "こんばんは",
  "moshi moshi",
  "もしもし",
  "yaho",
  "やほ",

  // Chinese
  "ni hao",
  "nihao",
  "你好",
  "哈喽",
  "嗨",

  // Korean
  "annyeong",
  "annyeonghaseyo",
  "안녕",
  "안녕하세요",
];

const THANKS_TERMS = [
  "makasih",
  "terima kasih",
  "trimakasih",
  "terimakasih",
  "thanks",
  "thank you",
  "thankyou",
  "thx",
  "tq",
  "ty",
  "appreciate it",
  "nice thanks",
  "sip makasih",
  "oke makasih",

  // Japanese
  "arigato",
  "arigatou",
  "ありがとう",
  "domo",
  "doumo",
  "sankyu",

  // Chinese
  "xie xie",
  "xiexie",
  "谢谢",

  // Korean
  "gomawo",
  "kamsahamnida",
  "감사",
  "감사합니다",

  // Other common
  "merci",
  "gracias",
];

const PRAISE_TERMS = [
  "good job",
  "nice",
  "nice one",
  "keren",
  "kereen",
  "bagus",
  "mantap",
  "mantul",
  "anjay",
  "anjir keren",
  "gokil",
  "goks",
  "gg",
  "kamu gg",
  "goat",
  "savage",
  "cool",
  "epic",
  "hebat",
  "pintar",
  "pinter",
  "smart",
  "cerdas",
  "jago",
  "pro",
  "the best",
  "best",
  "solid",
  "kece",
  "cakep",
  "love you",
  "ily",
  "luv u",
  "luv",
  "sayang",
  "baby",
  "gemes",
  "imut",
  "cute",
  "kawaii",
  "かわいい",
  "suki",
  "好き",
  "ai ni",
  "wo ai ni",
  "我爱你",
];

const IDENTITY_TERMS = [
  "siapa kamu",
  "kamu siapa",
  "lu siapa",
  "loe siapa",
  "anda siapa",
  "who are you",
  "what are you",
  "your name",
  "nama kamu siapa",
  "identitas kamu",
  "kamu bot",
  "kamu ai",
  "kamu manusia",
  "ini bot apa",
  "ini ai apa",
  "weebinai itu apa",
  "apa itu weebinai",
];

const STATUS_TERMS = [
  "lagi apa",
  "ngapain",
  "sibuk apa",
  "apa kabar",
  "gimana kabar",
  "how are you",
  "how r u",
  "hru",
  "are you ok",
  "are you okay",
  "you okay",
  "sehat",
  "baik",
  "genki",
  "元気",
  "daijoubu",
  "大丈夫",
  "kamu oke",
  "kamu baik",
];

const LAUGHTER_TERMS = [
  "wkwk",
  "wkwkwk",
  "wkwkwkwk",
  "haha",
  "hahaha",
  "hehe",
  "hehehe",
  "lol",
  "lmao",
  "xixi",
  "wk",
  "awok",
  "awokwok",
  "kwkw",
];

export const GREETING_RE = makeStartPattern(GREETING_TERMS);
export const THANKS_RE = makeLoosePattern(THANKS_TERMS);
export const PRAISE_RE = makeLoosePattern(PRAISE_TERMS);
export const IDENTITY_RE = makeLoosePattern(IDENTITY_TERMS);
export const STATUS_RE = makeLoosePattern(STATUS_TERMS);

export const SMALL_TALK_PATTERN = makeSmallTalkPattern([
  ...GREETING_TERMS,
  ...THANKS_TERMS,
  ...PRAISE_TERMS,
  ...IDENTITY_TERMS,
  ...STATUS_TERMS,
  ...LAUGHTER_TERMS,
]);

export function isPromptInjection(query: string) {
  return PROMPT_INJECTION_PATTERN.test(query);
}

export function isSmallTalk(query: string) {
  return SMALL_TALK_PATTERN.test(query);
}

export function hasContentIntent(query: string) {
  return CONTENT_INTENT_PATTERN.test(query);
}

export function isLikelyOffTopic(query: string) {
  const text = query.trim();

  if (!text) return false;

  // Prompt injection tetap diproses terpisah, jangan dianggap small talk.
  if (isPromptInjection(text)) return true;

  // Hard off-topic intent harus menang walau user menyelipkan kata anime.
  // Contoh: "cara bikin website anime" tetap pertanyaan coding, bukan katalog Weebin.
  if (
    makeLoosePattern([
      "coding",
      "ngoding",
      "source code",
      "programming",
      "pemrograman",
      "web",
      "website",
      "bikin web",
      "buat web",
      "frontend",
      "backend",
      "fullstack",
      "database",
      "sql",
      "api",
      "javascript",
      "typescript",
      "python",
      "php",
      "laravel",
      "react",
      "vue",
      "nodejs",
      "css",
      "html",
      "debug",
      "deploy",
      "server",
      "hosting",
      "domain",
      "github",
      "docker",
    ]).test(text)
  ) {
    return true;
  }

  // Kalau ada sinyal anime/donghua/episode, jangan anggap off-topic.
  // Contoh: "anime romance yang bikin galau" jangan kena OFF_TOPIC karena ada kata romance/galau.
  if (hasContentIntent(text)) return false;

  // Small talk seperti "love you", "apa kabar", "makasih" jangan dianggap off-topic.
  if (isSmallTalk(text)) return false;

  return OFF_TOPIC_PATTERN.test(text);
}
